spring:
  application:
    name: admin-server
  #  配置登录密码
  security:
    user:
      name: "admin"
      password: "admin"
  #  boot.admin.client
  mail:
    host: smtp.163.com
    username: liyuanzjutmaster@163.com
    password: BUFEWSMIEYISXJLG
  boot:
    admin:
      notify:
        mail:
          to: 1627739285@qq.com
          from: liyuanzjutmaster@163.com
server:
  port: 8769
eureka:
  client:
    registryFetchIntervalSeconds: 5 #eureka client间隔多久去拉取服务注册信息，默认为30秒
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10 #表示eureka client发送心跳给server端的频率 ，默认30秒
    health-check-url-path: /actuator/health
    metadata-map:
      user.name: admin #${spring.security.user.name}
      user.password: admin #${spring.security.user.password}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file: D:/log/sample-boot-application.log
#  pattern:
#      file: %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx
